apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewogICJhdXRocyIgOiB7CiAgICAiY29udGFpbmVyLXJlZ2lzdHJ5Lm9yYWNsZS5jb20iIDogewoKICAgIH0sCiAgICAiZ2hjci5pbyI6IHsKICAgICAgICJhdXRoIjoiWm5WcmNHbG5PbWRvY0Y4NWNtNXBTSGhXYkZsaWFXYzFRbXhTTjB4NmFFVkpaWHBsUTJ0bWNUWXlWVVpHWWprPSIKICAgIH0KICB9LAogICJjcmVkc1N0b3JlIiA6ICJkZXNrdG9wIgp9Cg==
type: kubernetes.io/dockerconfigjson
